# Generated by Django 6.0.6 on 2026-06-20 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=10)),
                ('model_used', models.CharField(help_text="e.g. 'gemini-2.0-flash'", max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_latency_seconds', models.FloatField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='core.pullrequest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('summarize', 'Summarize diff'), ('classify_risk', 'Classify risk'), ('match_reviewer', 'Match reviewer'), ('check_tests', 'Check tests included')], max_length=20)),
                ('step_order', models.PositiveSmallIntegerField(help_text='Execution order within the run, supports parallel steps sharing an order.')),
                ('prompt_sent', models.TextField(blank=True, help_text='Empty for non-LLM steps like check_tests.')),
                ('raw_response', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_seconds', models.FloatField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun')),
            ],
            options={
                'ordering': ['agent_run', 'step_order'],
            },
        ),
    ]
