# Generated by Django 6.0.6 on 2026-06-21 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('author_username', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=10)),
                ('diff_summary', models.TextField(blank=True, help_text='Raw diff stats or summary, not full diff text.')),
                ('opened_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_username', models.CharField(max_length=100, unique=True)),
                ('github_id', models.CharField(max_length=50, unique=True)),
                ('access_token_encrypted', models.TextField(help_text='GitHub OAuth access token, encrypted before storage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_was_correct', models.BooleanField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='core.developer')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='core.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="e.g. 'khilav/grocerybot'", max_length=255)),
                ('github_repo_id', models.CharField(max_length=50, unique=True)),
                ('webhook_active', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null until a Developer authenticates and claims this repo. May be discovered via webhook first.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.developer')),
            ],
            options={
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.repository'),
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_file_patterns', models.JSONField(default=list, help_text="List of file path patterns this reviewer frequently edits, e.g. ['*.py', 'frontend/*']")),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profiles', to='core.developer')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profiles', to='core.repository')),
            ],
            options={
                'unique_together': {('developer', 'repository')},
            },
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('trivial', 'Trivial'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('summary', models.TextField(help_text='Plain-English summary of what the diff does.')),
                ('tests_missing', models.BooleanField(default=False)),
                ('confidence', models.FloatField(help_text="Agent's self-reported confidence, 0.0 to 1.0.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='core.pullrequest')),
                ('suggested_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for', to='core.reviewerprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'github_pr_number')},
        ),
    ]
