# Generated by Django 6.0.6 on 2026-06-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="GitHub event type, e.g. 'pull_request', 'push'.", max_length=50)),
                ('delivery_id', models.CharField(help_text="GitHub's X-GitHub-Delivery header, used to detect duplicate deliveries.", max_length=100, unique=True)),
                ('raw_payload', models.JSONField(help_text='The full webhook payload, exactly as received.')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(blank=True, help_text='Set once this event has been linked to a specific PR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='core.pullrequest')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='core.repository')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
